### ISSUE TITLE
Support for a specific file in a gist

### ISSUE THREAD

**Issue by ringods** [tleunen/react-gist#1]
Github Gist's can contain multiple files. When you only want to include a specific file, there should be a second parameter allowing to pass the filename you want to see. 

Here is an example of a multi-file gist:
https://gist.github.com/ringods/5995ea726914f280afb3

This gist is used in this static Hugo blog article:
https://ringo.de-smet.name/2015/03/keep-chef-out-of-your-docker-containers/

Could you extend the gist component to support the filename?

**Comment by tleunen** [comment]
Hi @ringods,

Thanks for the suggestion. I'm not actively using the component anymore, but I'll try to add the feature when I get some time.

Feel free to submit a PR with that feature if you'd like too.

**Comment by ringods** [comment]
@tleunen contributed via #2. When you merge, could you also do a version bump and release to `npmjs.com`?

**Comment by tleunen** [comment]
Thanks @ringods! Published as v1.1.0 :)
